name: Pipeline

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  run-unit-and-integration-tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test --tests '*.*Unit*'

      - name: Run integration tests
        run: ./gradlew test --tests '*.*Integration*'

  deploy-to-staging-and-run-further-tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release' || (github.event_name == 'pull_request' && github.base_ref == 'release' && github.head_ref == 'main')
    needs: run-unit-and-integration-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman tests
        run: newman run src/test/system/Randomuser.postman_collection.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get project version
        run: echo "PROJECT_VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/spring
          tag: ${{ env.PROJECT_VERSION }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/ArgoCD_GitOps
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          ref: main

      - name: Update image tag in values.yml
        run: |
          sed -i "s/tag: .*/tag: ${{ env.PROJECT_VERSION }}/" values_staging.yml

      - name: Create branch
        run: |
          git checkout -b feature/production
          git push origin feature/production

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge feature/production into main"
          branch: main
          title: "Merge feature/production into main"
          body: |
            @ZeRoOW14, überprüfe

      - name: Wait for ArgoCD deployment
        run: |
          # Add commands to check the status of ArgoCD deployment here
          # You may use ArgoCD CLI or API to check the deployment status
          # Example:
          # argocd app wait <APP_NAME> --timeout 300

      - name: Run system tests
        run: |
          # Add the execution of further tests here 
          # You may use Newman for system testing
          # Example:
          # newman run collection.json -e environment.json

      - name: Delete feature branch after merge
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: git push origin --delete feature/production

  deploy-to-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/ArgoCD_GitOps
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          ref: main

      - name: Create feature branch
        run: git checkout -b feature/production

      - name: Update image tag with version from staging in production values.yml
        run: |
          version=$(grep 'tag:' values_staging.yml | awk '{print $2}')
          sed -i "s/tag: .*/tag: $version/" values_production.yml

      - name: Commit changes to GitOps repository
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add values_production.yml
          git commit -m "Deploy $version to production"
          git push origin HEAD:feature/production

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge feature/production into main"
          branch: main
          title: "Merge feature/production into main"
          body: |
            This pull request merges the changes from the feature/production branch into the main branch.
      
